### ISSUE TITLE
Auto hide beavour not initialised on first load

### ISSUE THREAD

**Issue by chriswatt** [heidji/ionic3-hidenav#1]
Hi heidji!

First off I would like to see many thanks for spending the time developing this plugin.

I managed to get the plugin mostly working besides one particular issue. When first navigating to my tabs page, the auto hide behavior doesn't initialise when scrolling, the header remains fixed as the user scrolls the content. If I switch to one of my other tabs, the auto hide functionality works fine for this new tab. If I then switch back to the first tab, the auto hide works as expected.

It's as if the auto hide functionality isn't being inititalised on page load and instead only when a tab switch has happened.

The only thing I could think of that may be related is my tabs page isn't the root page of my app. Another page loads first and the user has to manually navigate to the tabs.

I'm currently testing with version 0.0.11 from the npm database.

**Comment by heidji** [comment]
thanks Chris for opening the issue! 

I don't think that the page not being in root is an issue.. did you check the console log? did the module maybe give a warning about duplicate names? if not, then i would like to see some of your html where you use the directives please ..

**Comment by chriswatt** [comment]
I managed to figure out the problem. My `<ion-content>` had an `*ngIf` expression that was needed due to my view variables possibly not being set by the time the view has loaded.

Removing the `*ngIf` from `<ion-content>` and adding it to an entirely new `<div>` element inside solved the issue :+1:

**Comment by heidji** [comment]
Thats good to hear, I will also investigate why the ngIf disabled the scroll because in my opinion it shouldn't so I will leave this open until I (hopefully) get to the bottom of it.

Thanks for contributing and I sincerely hope my plugin helps you with your work. Don't hesitate to open more issues when you run into problems :)

**Comment by heidji** [comment]
I think now it's a Supertabs bug. If you add ion-content with ngIf into a Supertabs page, you cannot listen to the scroll events until you switch tabs.

**Comment by heidji** [comment]
I added a new bug report on the Supertabs page [here](https://github.com/zyra/ionic2-super-tabs/issues/362). I will close this issue because I literally can't do anything about it :D

Great stuff though!

**Comment by heidji** [comment]
new bug report on Ionic team [here](https://github.com/ionic-team/ionic-v3/issues/971)
